idf_component_register(
    SRCS 
        main.cpp
        app.cpp
        WiFiManager.cpp
        ProductService.cpp
        BarcodeReader.cpp
        product_cache.cpp
        fetchproducts.cpp
        product_cache.cpp
        ui/actions.c
        ui/screens.c
        ui/styles.c
        ui/images.c
        ui/vars.c
        ui/ui.c
    INCLUDE_DIRS
        .
        ui

)
